[project]
name = "product-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
    "sqlmodel>=0.0.34",
    "psycopg[binary]>=3.3.3",
    "opentelemetry-api>=1.40.0",
    "opentelemetry-sdk>=1.40.0",
    "opentelemetry-exporter-otlp>=1.40.0",
    "opentelemetry-instrumentation-grpc>=0.61b0",
]
