# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"b\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\timage_url\x18\x05 \x01(\t\"\x15\n\x13ListProductsRequest\"B\n\x14ListProductsResponse\x12*\n\x08products\x18\x01 \x03(\x0b\x32\x18.product.ProductResponse\"[\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\"(\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"\xac\x01\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05price\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x16\n\timage_url\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_priceB\x0e\n\x0c_descriptionB\x0c\n\n_image_url2\xfc\x02\n\x0eProductService\x12?\n\nGetProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12K\n\x0cListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12H\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12H\n\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponse\x12H\n\rDeleteProduct\x12\x17.product.ProductRequest\x1a\x1e.product.DeleteProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=26
  _globals['_PRODUCTREQUEST']._serialized_end=54
  _globals['_PRODUCTRESPONSE']._serialized_start=56
  _globals['_PRODUCTRESPONSE']._serialized_end=154
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=156
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=177
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=179
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=245
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=247
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=338
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=340
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=380
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=383
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=555
  _globals['_PRODUCTSERVICE']._serialized_start=558
  _globals['_PRODUCTSERVICE']._serialized_end=938
# @@protoc_insertion_point(module_scope)
