apiVersion: 1

policies:
  - orgId: 1
    receiver: ops-team
    group_by: ["alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: ops-team
        matchers:
          - severity = warning
        group_by: ["alertname", "name"]
